Add Deadlines to Output
GatorEducator/gatorgrade pull request #114
Opened 2023-03-01 01:57 UTC by burgess01

# Add Deadlines to Output

## Description

This PR allows you to add a deadline in MM/DD/YY HH:MM:SS format to the yml file. If this is included, then the output will tell the user how long they have until their assignment is due or how late it is. If there is no deadline then nothing changes about the output.

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @burgess01

2023-03-01 02:32 UTC, burgess01 commented
Here is an example of how the deadline section of the yml file would look like:
```yml
deadline: |
  03/1/23 12:00:00
---
```
Hours are in military time.
Here are two example outputs, one being for an on time assignment and one being late. I tested this with different dates using labs from 400.
```txt
✓  Delete the 'Add Your Name Here' prompt in the reflection file
✕  Write a minimum of 1000 meaningful words in the reflection
(..cut to save space..)
✕  The reflection.md in writing has at least 30 of the 'code_block' tag
✕  Have at least a specific minimum number of 10 commits in repository

-~- Your assignment is due in 0 days, 2 hours, 49 minutes, and 20 seconds. -~-

        ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━┓
        ┃ Passed 12/18 (67%) of checks for 
computer-science-400-fall-2022-p4-data-processing-burgess01! ┃
        ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━┛
```
```txt
✓  Ensure that the processor.py file exists in project/pylang
✓  Complete all TODOs, remove the TODO markers, and rewrite comments for 
processor.py
(... cut to save space)
✕  The reflection.md in writing has at least 30 of the 'code_block' tag
✕  Have at least a specific minimum number of 10 commits in repository

-~- Your assignment is late. The deadline was 0 days, 21 hours, 9 minutes, and 39 seconds ago. -~-

        ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━┓
        ┃ Passed 12/18 (67%) of checks for 
computer-science-400-fall-2022-p4-data-processing-burgess01! ┃
        ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━┛
```

Nothing from a cli standpoint would change from this PR.

2023-03-10 01:01 UTC, burgess01 commented
Deadlines are now included in both the json and markdown output:
```yaml
{"amount_correct": 12, "percentage_score": 67, "deadline": "Due in 0 days, 15 hours, 59 minutes, and 7 seconds.", (...)}
```
```txt
# Gatorgrade Insights

**Project Name:** computer-science-400-fall-2022-p4-data-processing-burgess01
**Amount Correct:** 12/18 (67%)
**Deadline:** Due in 0 days, 16 hours, 2 minutes, and 58 seconds.

## Passing Checks
(...)
```

2023-03-13 14:29 UTC, Michionlion requested changes

2023-03-13 14:29 UTC, Michionlion commented on gatorgrade/output/output.py
>  def run_checks(checks: List[Union[ShellCheck, GatorGraderCheck]], deadline) -> bool:
Looks like the function signature here might be missing a few of the needed parameters, as well as the `Args` part of the docstring.

2023-03-13 14:31 UTC, Michionlion reviewed
I do have concerns with how much data coupling we have now but I'm not sure there's a quick-and-easy solution to that. Other than that this looks decent!

2023-03-13 17:12 UTC, burgess01 commented
@Michionlion I was thinking the same thing. I wasn't sure of a better way to grab the data besides just passing it along like that. It seems like a waste to spend time trying to reparse again rather than just passing the variable through the different functions.

2023-04-17 01:36 UTC, Yanqiao4396 commented
I believe the output is good. I feel the same like you both that the data coupling is becoming a serious problem in this project. We are adding more and more parameters parsed into functions.  For example, one of our most important functions `run_checks` is currently accepting 3 parameters `checks, report, deadline` and will probably accept 4 or more after we add more features while it was only designed to accept one `checks` at first.

Here I am discovering solutions. Can we do something like after parsing `gatorgrade` yaml file and `build` yaml file, we create an instance from a class where `checks, report, deadline` and all other new feature inputs will be attributes of that class. At the same time, we add execution functions related to certain attribute in the same class. So that we only need to parse the instance into a function and use a high-level function (that function is currently `run_checks`) to call certain methods if certain attributes are set to be True

2026-06-11 20:55 UTC, gkapfham commented
This PR is now out of date, but I can still se benefits to adding this feature.

2026-07-02 20:20 UTC, gkapfham commented
This PR's feature was implemented and merged through another PR. As such, I am going to close this PR and not merged it. Thanks for your understanding!

2026-07-02 20:20 UTC, closed without merging