feat: filter specific checks
GatorEducator/gatorgrade pull request #150
Opened 2024-10-31 18:47 UTC by Chezka109

# Filtering Specific Checks

## Description

This feature adds the ability to filter GatorGrade results to show only the failing checks when running the command. By including a flag such as `--show-failures`, users will be able to see just the errors, which will make it easier to focus on the areas that need improvement without sifting through the passing checks. In addition to this, users can use the flag `--check-include "{argument}"` to show only a specific check and `--check-exclude "{argument}"` to remove specific checks when gatorgrade runs.

**Screenshots**:

- `gatorgrade --show-failures`
<img width="549" alt="Screenshot 2024-10-31 at 2 38 00 PM" src="https://github.com/user-attachments/assets/84642c19-3cf2-4e03-b801-b10cccbf42a0">

- `gatorgrade --check-include "Ensure that Question 1"`
<img width="545" alt="Screenshot 2024-10-31 at 2 39 34 PM" src="https://github.com/user-attachments/assets/abadb6ee-40a4-4125-97e0-d1168b83aa46">

- `gatorgrade --check-exclude "Ensure that Question 1"`
<img width="523" alt="Screenshot 2024-10-31 at 2 40 24 PM" src="https://github.com/user-attachments/assets/1704d051-e38c-4977-9b16-e193fa8aae4a">

**NOTE:** Arguments for the `--check-include` and `--check-exclude` uses fuzzy clustering. This means that:
If a check appears as: `Complete all TODOs, remove the TODO markers, and rewrite comments for question_one.py`
A user may write the command as any of the following:
- `gatorgrade --check-include "Complete all TODOs"`
- `gatorgrade --check-include "Complete all todos"`
- `gatorgrade --check-include "CompleTe all Todos"`
- `gatorgrade --check-include "Co"`
- `gatorgrade --check-include "TODO"` 

## Linked Issues

closes: #139 

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @Chezka109
- @HoangTrang150302

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

2024-11-06 15:01 UTC, Chezka109 commented
@gkapfham i've been trying to fix the build for a couple weeks now and still can't figure it out. according to the workflow, there's something wrong with the `parse_config`. 

here is the code block for the failure:
```cmd
=================================== FAILURES ===================================
___________ test_parse_config_gg_check_in_file_context_contains_file ___________

    def test_parse_config_gg_check_in_file_context_contains_file():
        """Test to make sure that the file context is included in the GatorGrader arguments."""
        # Given a configuration file with a GatorGrader check within a file context
        config = Path("tests/input/yml_test_files/gatorgrade_one_gg_check_in_file.yml")
        # When parse_config is run
        output = parse_config(config)
        # Then the file path should be in the GatorGrader arguments
>       assert "file.py" in output[0].gg_args
E       AttributeError: 'list' object has no attribute 'gg_args'

tests/input/test_input_gg_checks.py:17: AttributeError
=========================== short test summary info ============================
FAILED tests/input/test_input_gg_checks.py::test_parse_config_gg_check_in_file_context_contains_file - AttributeError: 'list' object has no attribute 'gg_args'
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 1 failed in 0.39s ===============================
Error: Process completed with exit code 1.
```

2024-11-08 15:40 UTC, boulais01 commented
@Chezka109 Since this is failing/incomplete, consider marking this as a draft.

2024-11-19 12:55 UTC, gkapfham commented
Hello @Chezka109 can you please ensure that you first have reviews from two students who did not work on this feature and from at least one student technical leader?

2024-11-21 20:24 UTC, Chezka109 commented
@gkapfham, the coverage badge doesn't work because the coverage.json file no longer exists. I can fix it so that it doesn't need a .json file to work! I don't know why the version badge stopped working, I will take a look.

2024-11-21 21:20 UTC, CalebKendra commented
@Chezka109 do you now need reviews from TL's/other students? please add as reviewer if needed

2024-11-25 03:41 UTC, rebekahrudd commented
I tried to test this PR but I keep getting the error that there is no module called `thefuzz`. I have installed `thefuzz` with the command `pip install thefuzz`. 

Here is a screenshot that shows that `thefuzz` is installed and that when running it doesn't work:
![image](https://github.com/user-attachments/assets/8d7c8ac6-24e7-4c17-ba01-89868523333f)

It's also worth considering that the package `thefuzz` has a failing build right now. I don't know if affecting why it isn't working for me. Here is the link to `thefuzz` GitHub page: [https://github.com/seatgeek/thefuzz](https://github.com/seatgeek/thefuzz)

2024-12-05 21:15 UTC, hemanialaparthi requested changes
Hi @Chezka109, I tried testing out your PR and it gives me this output:

```
hemanialaparthi@Hemanis-MacBook-Air exam % gatorgrade --check-include "Complete all TODOs"
Traceback (most recent call last):
  File "/Users/hemanialaparthi/.local/bin/gatorgrade", line 7, in <module>
    from gatorgrade.main import app
  File "/Users/hemanialaparthi/Library/Application Support/pipx/venvs/gatorgrade/lib/python3.13/site-packages/gatorgrade/main.py", line 8, in <module>
    from gatorgrade.input.parse_config import parse_config
  File "/Users/hemanialaparthi/Library/Application Support/pipx/venvs/gatorgrade/lib/python3.13/site-packages/gatorgrade/input/parse_config.py", line 5, in <module>
    from thefuzz import fuzz
ModuleNotFoundError: No module named 'thefuzz'
```


I would consider resolving this issue and also fixing the conflicts in the `pyproject.toml`

2024-12-05 21:53 UTC, rebekahrudd approved these changes
This worked on my Linux computer.

Here is two screenshots of output from running different commands that @Chezka109 listed:
![test1](https://github.com/user-attachments/assets/62d53aae-322b-4527-92d1-c6f11d6ac5a7)
![test2](https://github.com/user-attachments/assets/d063701d-eb48-4fce-a5a1-8f27ec491dcc)

2024-12-06 03:18 UTC, hemanialaparthi approved these changes
Hi! This PR LGTM! I tested it out on my `mac` and it works as intended. Good work!!

![image](https://github.com/user-attachments/assets/bec47473-e23f-4ff7-a3bc-c61e4c6894e4)

2026-06-11 20:56 UTC, gkapfham commented
This PR is out of date but I can see benefits to add this feature.

2026-07-17 23:28 UTC, gkapfham commented
Since there is a new PR with additional features and a revised version of these features that aligns with the current implementation, I am going to close this PR. Thanks!

2026-07-17 23:28 UTC, closed without merging