Fix: code coverage percent for gatorgrade files
GatorEducator/gatorgrade pull request #157
Opened 2024-11-11 21:56 UTC by hannahb09

# Code Coverage

## Description
This is a fix so that gatorgrade when running the code coverage gets the right files which is gatorgrade files and leaves out empty files that have no code in the over all percentage.  These are the code commands that should work. ```poetry run task coverage``` I got on linux 
![Screenshot from 2024-11-11 16-50-29](https://github.com/user-attachments/assets/5e7dffac-65c9-453b-8d5e-6275522d2fcd)
![Screenshot from 2024-11-11 16-51-11](https://github.com/user-attachments/assets/c3d17a63-78b7-463b-9c67-91b971a747fb)
![Screenshot from 2024-11-11 16-51-16](https://github.com/user-attachments/assets/80ee5f01-e3b9-40ca-b857-8b9ef19a8a94)
for ```poetry run task test``` I got
![Screenshot from 2024-11-11 16-55-23](https://github.com/user-attachments/assets/5b55e42a-c147-46b1-81a1-55abce386252)
![Screenshot from 2024-11-11 16-55-31](https://github.com/user-attachments/assets/34e86b29-f2b5-46e9-9894-3c3c62ce3045)
![Screenshot from 2024-11-11 16-55-37](https://github.com/user-attachments/assets/b5557301-f031-4555-b4f9-e6d9aa89c0c8)

## Type of Change

- [ ] Feature
- [X ] Bug fix
- [ ] Documentation

2024-11-14 21:49 UTC, PCain02 requested changes
Based on the conversations from class today it looks like uploading the `coverage.json`  is not a viable option and our coverage badge should be generated in actions and based on that. I was able to the coverage command to run however so that is good. I think we need to have more discussions about what to do about the `.json` file.

2024-11-19 12:56 UTC, gkapfham commented
Hello @hannahb09 there is at least one revision that has been requested, can you please investigate this further?

2024-11-21 02:12 UTC, PCain02 commented
So what is the plan going forward with coverage? Does it still work but no `json` is made or is it getting ignored in the `.gitignore` now? Because we will continue to run into problems with people commiting large `json` files on accident if it is not ignored and that adds to the size of our repo. Please keep me updated on the plan going forward! I'll take the changes requested off once I know this coverage process is resolved. Also is the same issue in `execexam`?

2024-11-22 18:55 UTC, boulais01 commented
Hi @hannahb09, you've requested review but you haven't addressed the comments/questions here. Please do so.

2024-11-22 19:05 UTC, hannahb09 commented
> So what is the plan going forward with coverage? Does it still work but no `json` is made or is it getting ignored in the `.gitignore` now? Because we will continue to run into problems with people commiting large `json` files on accident if it is not ignored and that adds to the size of our repo. Please keep me updated on the plan going forward! I'll take the changes requested off once I know this coverage process is resolved. Also is the same issue in `execexam`?

We are ignoring the coverage.json file now on it has been added to the gitignore file and Kapfhammer has said we will not commit it from now on.

2024-11-26 00:56 UTC, PCain02 requested changes
I got an error when trying to run `poetry run task coverage` on Windows 10

![image](https://github.com/user-attachments/assets/b19f6bc0-c8d3-4658-85e3-fd3120d33c68)

```
C:\Users\Palla\AppData\Local\pypoetry\Cache\virtualenvs\gatorgrade-QO4nVhz5-py3.12\Lib\site-packages\_pytest\config\__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
```

2024-11-26 01:01 UTC, PCain02 commented
I also noticed the coverage commands in the `pyproject.toml` file should be updated unless these are the correct commands and they just aren't working. 
```
check-command = { var = "ruff check {project} {tests}", recursive = true }
-test-command = "pytest -s --cov-context=test --cov-fail-under=50 --cov-config .coveragerc --cov-report term-missing --cov-report json --ccoverageov --cov-branch"
coverage-test-command-silent = "pytest -x --show-capture=no --cov-config .coveragerc --cov-report term-missing --cov-report json --cov --cov-branch"
```

2024-11-26 01:09 UTC, PCain02 commented
> I got an error when trying to run `poetry run task coverage` on Windows 10
> 
> ![image](https://private-user-images.githubusercontent.com/89534001/389749051-b19f6bc0-c8d3-4658-85e3-fd3120d33c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODI5MTEsIm5iZiI6MTczMjU4MjYxMSwicGF0aCI6Ii84OTUzNDAwMS8zODk3NDkwNTEtYjE5ZjZiYzAtYzhkMy00NjU4LTg1ZTMtZmQzMTIwZDMzYzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMThjYTgxNDE0ZDFhODJhODAwZDM1NGE1MjhlOTk2NDVmYzJmYjRhYzQ1NWIwYmE0YmFlNjk1YjcwZTQ1MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EgSG7liurj6fAW9WvqnOmEm8AfvDshUKaB7jUGDZVa8)
> 
> ```
> C:\Users\Palla\AppData\Local\pypoetry\Cache\virtualenvs\gatorgrade-QO4nVhz5-py3.12\Lib\site-packages\_pytest\config\__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
> Plugin: helpconfig, Hook: pytest_cmdline_parse
> UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
> For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
>   config = pluginmanager.hook.pytest_cmdline_parse(
> ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
> ```

I think part of it is `json` isn't a valid option for a coverage report in this case. I was able to generate a `coverage.xml` by changing a couple things but I figure that messes with the pipeline by changing file types so that is not a good fix.

2024-11-26 01:23 UTC, hannahb09 commented
> > I got an error when trying to run `poetry run task coverage` on Windows 10
> > ![image](https://private-user-images.githubusercontent.com/89534001/389749051-b19f6bc0-c8d3-4658-85e3-fd3120d33c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODI5MTEsIm5iZiI6MTczMjU4MjYxMSwicGF0aCI6Ii84OTUzNDAwMS8zODk3NDkwNTEtYjE5ZjZiYzAtYzhkMy00NjU4LTg1ZTMtZmQzMTIwZDMzYzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMThjYTgxNDE0ZDFhODJhODAwZDM1NGE1MjhlOTk2NDVmYzJmYjRhYzQ1NWIwYmE0YmFlNjk1YjcwZTQ1MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EgSG7liurj6fAW9WvqnOmEm8AfvDshUKaB7jUGDZVa8)
> > ```
> > C:\Users\Palla\AppData\Local\pypoetry\Cache\virtualenvs\gatorgrade-QO4nVhz5-py3.12\Lib\site-packages\_pytest\config\__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
> > Plugin: helpconfig, Hook: pytest_cmdline_parse
> > UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> > pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
> > For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
> >   config = pluginmanager.hook.pytest_cmdline_parse(
> > ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> > pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
> > ```
> 
> I think part of it is `json` isn't a valid option for a coverage report in this case. I was able to generate a `coverage.xml` by changing a couple things but I figure that messes with the pipeline by changing file types so that is not a good fix.

I do not understand what is going wrong what you suggested is what is already in the pyproject.toml file. It be important to see if this works on Mac or the error still happens

2024-11-26 01:25 UTC, PCain02 commented
> > > I got an error when trying to run `poetry run task coverage` on Windows 10
> > > ![image](https://private-user-images.githubusercontent.com/89534001/389749051-b19f6bc0-c8d3-4658-85e3-fd3120d33c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODI5MTEsIm5iZiI6MTczMjU4MjYxMSwicGF0aCI6Ii84OTUzNDAwMS8zODk3NDkwNTEtYjE5ZjZiYzAtYzhkMy00NjU4LTg1ZTMtZmQzMTIwZDMzYzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMThjYTgxNDE0ZDFhODJhODAwZDM1NGE1MjhlOTk2NDVmYzJmYjRhYzQ1NWIwYmE0YmFlNjk1YjcwZTQ1MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EgSG7liurj6fAW9WvqnOmEm8AfvDshUKaB7jUGDZVa8)
> > > ```
> > > C:\Users\Palla\AppData\Local\pypoetry\Cache\virtualenvs\gatorgrade-QO4nVhz5-py3.12\Lib\site-packages\_pytest\config\__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
> > > Plugin: helpconfig, Hook: pytest_cmdline_parse
> > > UsageError: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> > > pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
> > > For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
> > >   config = pluginmanager.hook.pytest_cmdline_parse(
> > > ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
> > > pytest: error: argument --cov-report: invalid choice: "json" (choose from "['term', 'term-missing', 'annotate', 'html', 'xml']")
> > > ```
> > 
> > 
> > I think part of it is `json` isn't a valid option for a coverage report in this case. I was able to generate a `coverage.xml` by changing a couple things but I figure that messes with the pipeline by changing file types so that is not a good fix.
> 
> I do not understand what is going wrong what you suggested is what is already in the pyproject.toml file. It be important to see if this works on Mac or the error still happens

Yeah I am not convinced the `toml` file is set up properly.

2024-12-03 05:03 UTC, hemanialaparthi commented
tested this on a mac and had the same issue where i tried to run the command `poetry run task coverage` and this was my output:

![image](https://github.com/user-attachments/assets/c40c50d0-e234-4554-860f-545d0285ca27)

but here is the other command: `poetry run task test`, which looks like it works as intended:
![image](https://github.com/user-attachments/assets/20266b9a-4600-42bb-ad4e-931ea220c9a6)

2024-12-03 05:30 UTC, hannahb09 commented
> tested this on a mac and had the same issue where i tried to run the command `poetry run task coverage` and this was my output:
> 
> ![image](https://private-user-images.githubusercontent.com/143897209/391818650-c40c50d0-e234-4554-860f-545d0285ca27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDM5NjYsIm5iZiI6MTczMzIwMzY2NiwicGF0aCI6Ii8xNDM4OTcyMDkvMzkxODE4NjUwLWM0MGM1MGQwLWUyMzQtNDU1NC04NjBmLTU0NWQwMjg1Y2EyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNTI3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjRhYjE5YWExMzhiZmRlZjE5M2Q4ODFjNjUzMmM0ZjliOTMyNDhjZjgyOTIwMjMxMGI4NDcxNWU0NDFkNTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NFTlA1wkZEymPb9wzJGHRu7oOj8GbA0n4YTL7bpAA3k)
> 
> but here is the other command: `poetry run task test`, which looks like it works as intended: ![image](https://private-user-images.githubusercontent.com/143897209/391818834-20266b9a-4600-42bb-ad4e-931ea220c9a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDM5NjYsIm5iZiI6MTczMzIwMzY2NiwicGF0aCI6Ii8xNDM4OTcyMDkvMzkxODE4ODM0LTIwMjY2YjlhLTQ2MDAtNDJiYi1hZDRlLTkzMWVhMjIwYzlhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNTI3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2FmYjFjMDBiZGU2N2MyMjY2YThjYmM5NTEyNDUxMTg0Nzg3NzRmYTU3YWQ1M2MxYTY2NzlkNmQwMGEwNzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rtWneTDHKKlxlW4oEvU8JsrCBlSBtnW1Do8uOpX2TxQ)

I updated it so now it show work poetry run task coverage. Some of the pytest in pyproject.toml needed the numbers to be upped so it could run properly. There should be no json error now.

2024-12-05 20:26 UTC, CalebKendra approved these changes
LGTM, `poetry run task coverage` and `poetry run task coverage-silent` work well on Ubuntu

2024-12-05 20:35 UTC, PCain02 requested changes
![image](https://github.com/user-attachments/assets/66b2cdd8-36e3-42d1-b629-aa587bebb973)

There issues with the test cases. This is not your bug but still needs fixed. What is happening is that there is a test that wants gatorgrade to fail a check but it is displaying all this output! That is not good because it looks like things are failing! Please fix the `toml` file to update the commands.

2024-12-05 21:18 UTC, hannahb09 commented
> ![image](https://private-user-images.githubusercontent.com/89534001/392986213-66b2cdd8-36e3-42d1-b629-aa587bebb973.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MzM2NDgsIm5iZiI6MTczMzQzMzM0OCwicGF0aCI6Ii84OTUzNDAwMS8zOTI5ODYyMTMtNjZiMmNkZDgtMzZlMy00MmQxLWI2MjktYWE1ODdiZWJiOTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDIxMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTMzZWU0YWQ5NTA4NjRjZjQ0NGFlNGE2MDdlODJhMmNkOTY5YzUxMDlkZmVjM2ZmZjIzMDE2Y2VhNzAyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v7JyOhBanvSScGIk79E82ARAbTHzIrF25iHa_Al9h6U)
> 
> There issues with the test cases. This is not your bug but still needs fixed. What is happening is that there is a test that wants `gatorgrade` to fail a check but it is displaying all this output! That is not good because it looks like things are failing! Please fix the `toml` file to update the commands.

poetry run task test-silent makes the command work where the test just tells you how many passes.

2026-01-04 00:33 UTC, closed without merging

2026-01-04 00:33 UTC, gkapfham commented
I have updated the system to use `uv` and I added test cases to achieve a coverage level of about 97%. Since we are no longer going to use `poetry` to manage this project and there are now tests that help to increase coverage, I am going to close this issue. Finally, it is worth pointing out that this project does not currently run test coverage monitoring in GitHub Actions and it does not have a badge in the README.md file that reports coverage. However, those can be other issues that are addressed in the future!