GatorGrade Motivator
GatorEducator/gatorgrade pull request #158
Opened 2024-11-13 14:47 UTC by PhilipOlwoc

# GatorGrade Motivator

## Description

In this feature a motivational message is meant to print when the user types --motivation. The point of the feature is meant to give students a little motivation when they are lacking in it. The feature is meant to print a message at 25%-50%, at 50%-75% and 75% onwards. Currently the quotes are hardcoded in a separate yaml file of which the professor can access and change if needed. This is an opt in feature so students would have to run the --motivation command to see the message. Below is the command needed to run the motivational quote.

![image](https://github.com/user-attachments/assets/d51438ad-c2bc-4a38-9d78-4ebb296e9d0f)

## Type of Change

- [X] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @PhilipOlwoc

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

2024-11-21 02:09 UTC, PCain02 requested changes
Hey @PhilipOlwoc it still says there are merge conflicts to resolve. There is a handy button below this conversation that says "resolve conflicts" and after you have you have to mark them as resolved! Hope this helps!

2024-11-21 18:23 UTC, PhilipOlwoc commented
hello @PCain02 and @gkapfham I believe I have fixed the merge conflicts.

2024-11-24 22:50 UTC, PhilipOlwoc commented
@CalebKendra I believe I fixed that issue, it should print normally now.

2024-11-25 04:03 UTC, rebekahrudd approved these changes
This worked on my Linux computer:
![image](https://github.com/user-attachments/assets/9932c434-6401-42fd-bcb5-cbc602309db5)

2024-12-05 20:57 UTC, CalebKendra requested changes
I got the following error when running `gatorgrade --config config/gatorgrade.yml` with or without the motivator:

```
╭─────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────────────────╮
│ /home/caleb/.pyenv/versions/3.12.7/lib/python3.12/site-packages/gatorgrade/main.py:67 in gatorgrade                                                                                                             │
│                                                                                                                                                                                                                 │
│    64 │   │   # there are valid checks and thus the                                            ╭───────────────────────────────────────── locals ──────────────────────────────────────────╮                    │
│    65 │   │   # tool should run them with run_checks                                           │         checks = [                                                                        │                    │
│    66 │   │   if len(checks) > 0:                                                              │                  │   <gatorgrade.input.checks.GatorGraderCheck object at 0x73f430edeb40>, │                    │
│ ❱  67 │   │   │   checks_status = run_checks(checks, report, run_status_bar, no_status_bar, ru │                  │   <gatorgrade.input.checks.GatorGraderCheck object at 0x73f4311e9340>, │                    │
│    68 │   │   # no checks were created and this means                                          │                  │   <gatorgrade.input.checks.GatorGraderCheck object at 0x73f431021340>, │                    │
│    69 │   │   # that, most likely, the file was not                                            │                  │   <gatorgrade.input.checks.GatorGraderCheck object at 0x73f43087f560>, │                    │
│    70 │   │   # valid and thus the tool cannot run checks                                      │                  │   <gatorgrade.input.checks.GatorGraderCheck object at 0x73f43087f4d0>, │                    │
│                                                                                                │                  │   <gatorgrade.input.checks.GatorGraderCheck object at 0x73f43087f500>  │                    │
│                                                                                                │                  ]                                                                        │                    │
│                                                                                                │            ctx = <click.core.Context object at 0x73f431bdb8c0>                            │                    │
│                                                                                                │       filename = PosixPath('config/gatorgrade.yml')                                       │                    │
│                                                                                                │  no_status_bar = False                                                                    │                    │
│                                                                                                │         report = (None, None, None)                                                       │                    │
│                                                                                                │ run_motivation = True                                                                     │                    │
│                                                                                                │ run_status_bar = False                                                                    │                    │
│                                                                                                ╰───────────────────────────────────────────────────────────────────────────────────────────╯                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: run_checks() takes 2 positional arguments but 5 were given
```

2025-01-22 19:07 UTC, closed without merging