Parse generated YAML file
GatorEducator/gatorgrade pull request #48
Opened 2022-04-19 20:41 UTC by Jacob-Allebach

# Parse generated YAML file

## Description

This pull request adds a function that uses PyYaml to parse the information from a given YAML file and returns the stored data so that it can be used later.

## Linked Issues

## Type of Change

- [x] Feature
- [ ] Bug fix
- [ ] Documentation

## Contributors

- @Jacob-Allebach 

## Reminder

 - All GitHub Actions should be in a passing state before any pull request is merged.
 - All PRs must be reviewed by at least one team member and one member of the Integration team!
 - Any issues this PR closes are tagged in the description!

2022-04-20 16:11 UTC, PaigeCD requested changes
Hi, Jacob. I have some quick changes to request before getting into the nitty-gritty of the code:
- Be sure to resolve the file's conflicts.
- Please merge main into your branch to get the poetry file and workflows!

2022-04-22 15:08 UTC, noorbuchi requested changes
Hello! Thanks for your work in  setting this up. Here are few suggestions.

2022-04-22 15:08 UTC, noorbuchi commented on gatorgrade/input/in_file_path.py
> +        return data_holder
I think this code can be simplified by doing this:
```suggestion
        return list(data)
```

2022-04-26 19:49 UTC, noorbuchi commented
Note that the build is failing, can you please investigate this and try to fix it before merging. Thanks!

2022-04-27 22:52 UTC, mariakimheinert commented
Hello @Jacob-Allebach, just want to check in with you about this PR since it has now been open for 8 days. It appears that the code you have included in this PR does not process the data that is read from the `gatorgrade.yml` file into the "list of tuples" format that your team discussed. It is my understanding that @tuduun is expecting this formatted data for the function he is currently writing. Do you plan to add additional changes to this PR or should it be reviewed?

2022-04-28 00:34 UTC, Jacob-Allebach commented
> Hello @Jacob-Allebach, I just want to check in with you about this PR since it has now been open for 8 days. It appears that the code you have included in this PR does not process the data that is read from the `gatorgrade.yml` file into the "list of tuples" format that your team discussed. It is my understanding that @tuduun is expecting this formatted data for the function he is currently writing. Do you plan to add additional changes to this PR or should it be reviewed?

Yes, this code just parses the YAML file and gets the raw data. I'm planning on making a separate pull request for the other function I'm writing that will format that data into the list of tuples, but it's not completed quite yet. If you think that should also be included in this pull request, I would be fine with adding it to this one once that is completed.

2022-04-28 16:24 UTC, noorbuchi approved these changes
As long as the team is on the same page regarding this PR and has a plan to use the function you've included here, then I think it's good to merge this. However, please make sure to address all questions brought up by @mariakimheinert before merging. Thanks for all your work!

2022-04-28 16:30 UTC, mariakimheinert commented
@Jacob-Allebach, I agree with @noorbuchi. It's fine to merge this function in first and then open another PR for the other function you plan to write. @laurennevill, @Michionlion, @PaigeCD, @LiamBlack3, would you please review this PR at your earliest convenience?

2022-04-28 16:54 UTC, PaigeCD approved these changes

2022-04-29 18:11 UTC, Michionlion approved these changes
This looks good, great work!

2022-04-29 18:12 UTC, merged